# Generated by Django 6.0.3 on 2026-03-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='field_id',
            new_name='file_id',
        ),
    ]
